name: Variable Usecase Workflow

on:
  workflow_dispatch:
  push:
    branches: # This key is required to list branches
      - master
      - variables_example-_branch
env:
  name: Ranjith
  course: Devops
jobs:
   job1_printing_variable_name:
     runs-on: ubuntu-latest
     env:
       os: Linux
     steps:
       - name: step1_Usecase_for_variables_name # Added a space before 'name'
         env:
           topic: Devops
         run: |
          echo "My name is $name" >> $GITHUB_STEP_SUMMARY
          echo "$name is leading the class for $topic" >> $GITHUB_STEP_SUMMARY
          echo "$We use ${{ var.CICD_TOOL }} for SDLC automation." >> $GITHUB_STEP_SUMMARY
          
       - name: step2_Usecase_for_variables_name # Added a space before 'name'
         env:
           topic: SRE
         run: |
          echo "We learn $os as a Operating System" >> $GITHUB_STEP_SUMMARY
          echo "$name is leading the class for $topic" >> $GITHUB_STEP_SUMMARY
    
   job2_printing_variable_value:
     runs-on: ubuntu-latest
     env:
       flavor: ubuntu
       os: Windows
     steps:
       - name: step1_Usecase_for_variables_value
         run: |
           echo "My name is $name" >> $GITHUB_STEP_SUMMARY
           echo "$course is the topic" >> $GITHUB_STEP_SUMMARY
           echo "We learn $os with $flavor for our commands practice" >> $GITHUB_STEP_SUMMARY

