name: Variable Usecase Workflow

on:
  workflow_dispatch:
  push:
    branches: # This key is required to list branches
      - master
      - variables_example-_branch
env:
  name: Rajesh
jobs:
   testing_variable_job:
     runs-on: ubuntu-latest
     steps:
       - name: Usecase_for_variables # Added a space before 'name'
         run: |
          echo "My name is $name" >> $GITHUB_STEP_SUMMARY
          echo "$name is leading the class for Devops" >> $GITHUB_STEP_SUMMARY

