name: Variable Usecase Workflow

on:
  workflow_dispatch:
  
  push:
    - master
    - variables_example-_branch

  
 jobs:
   testing_variable_job:
     runs-on: ubuntu-latest

     steps:
       -name: Usecase_for_variables
         run: echo "My name is Ranjith"
    
